name: PRU
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - async-timeout=4.0.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.14.6
  - charset-normalizer=2.1.1
  - click=8.1.7
  - colorama=0.4.5
  - comm=0.2.2
  - cryptography=37.0.2
  - cudatoolkit=11.6.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - deprecated=1.2.13
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.4.8
  - ffmpeg=4.3
  - fontconfig=2.14.0
  - fonttools=4.37.1
  - freetype=2.10.4
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=4.11.4
  - intel-openmp=2021.4.0
  - ipykernel=6.29.5
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=12.1.0
  - libiconv=1.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.7
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.6.0
  - nettle=3.6
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - packaging=21.3
  - pandas=1.4.3
  - parso=0.8.4
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=22.1.2
  - platformdirs=4.3.2
  - prompt-toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pygments=2.18.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python_abi=3.9
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - pytz=2022.1
  - pyzmq=25.1.2
  - qt=5.9.7
  - readline=8.1.2
  - redis=5.0.3
  - redis-py=4.3.4
  - requests=2.28.1
  - scikit-learn=1.1.3
  - scikit-surprise=1.1.2
  - scipy=1.7.3
  - setuptools=63.4.1
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.39.2
  - stack_data=0.6.2
  - threadpoolctl=3.5.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.14.3
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - wcwidth=0.2.13
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.5
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.0
